name: example-basic
on: [push]
jobs:
  basic-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: actions/checkout@v2
        with:
          working-directory: https://github.com/Foundant/cypress-tests/tree/trunk/UITest
          build: npx cypress info
